server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: app
          __path__: /logs/*.log
    pipeline_stages:
      - regex:
          expression: 'trace_id=(?P<trace_id>[0-9a-f]+).*span_id=(?P<span_id>[0-9a-f]+)'
      - labels:
          trace_id:
          span_id:
